"""tgbot

Revision ID: 14e81536afad
Revises: f61a4b83b0e0
Create Date: 2022-10-08 17:49:09.584755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e81536afad'
down_revision = 'f61a4b83b0e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
