"""tgbot okveds

Revision ID: dd05ff89ee80
Revises: 757d04d80adf
Create Date: 2022-10-08 18:01:52.362608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd05ff89ee80'
down_revision = '757d04d80adf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('okveds', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'okveds')
    # ### end Alembic commands ###
